---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgCA/jwML94/StqWml8wqFRJVkQu3L8gWDA53RmERAXvCsBKMRHqKh6ZG/kJmfMewMEAOJwKrDEs/duJH8NXavIO6To2ZU4HFamvabYuceooW/d4Bu0AP7GVxLlmeBbTDt4Fp+Xj9utJOTOmmltksvHbT9gAP07UN1XpJclwrC5lgQOHuTC0vngShLstngHpIkd5i74+z6qEM771e6CpuCM9MYH7YOuXfj7AMn4dgObE2liKsyp3ZqjIUwzs225zhzCbIJxMb5jAyr2RWHPsQ+AQOtLANFPYlYFL11lsUuPbymzN74g30bAIjvBVRN6akJM+0074b9vvaWx35HQhq56skFJJIBvtnBKx1MRYXMETiyVGW4eeblw/xQiUzGq4JKUyrKxCzauzwV1cV2oRXzPVukTqsQesn+iXcnFHJ9pyGvEHB029a8FTyqfCVWBgjdHsJ+JUT1rJm7fY0QGl/klCojSJpUYBZtFFqPFNigZhm4hqVIt3Gyip8CqxqNNNegBye3IoPHaZSzCrMXmJztpQvKDvfDAzQprw0rQNl6iRZ4gjcxzxgRGTJZWygVCpAl0IYQJ2b6kMcoza7jX/TRc+iQ1uh9IrmaZ2vc/oXo7GPWT+/YfuY9ID9Vpn4mA1usOD7kAQ8Xb2tf68jzqIBKqzZqzu8uiBKIYVl8hZ0FmS26vXLBM2ZNJ8+llIJj01RA+vBUpX+iA12ZokAaOO8irWrGF6oL8/rNb5MPl7cvPDS+ZwqUiVpvfseisJbY5Y/SwftQh2mwkxG+8Oer0KAYQobQEGz0j4TJ7U/XLkivoHv5WglMDOFTsSzSdFIKffGDxAChJSZtUQSSZWCa+WTmXf8Q9m9HiGUAC+
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
