---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgAMXbi8IlKzdwRzD9L6T4LL9kCeWP1gaRXeQ4yed+yPOceYLouepGHNY2nqAZNRBucrrKSvyiX9lSDRjGSYm/Vs44Pb/y9hSjDKdlPAAIIkkGpMY01OHk6wLFbYka3IN2UopseECZpdNEZRday+3WTftNwxjQ0P3o8XfIzUd9ryYcXZ0FbIonGHI0e92EHAcQO50kSVaXyzkUQeKOriZAmNNK9locrAH4JWvCYZGxsv8ciFjMbMpnaHiA0V+2dZcLYTzszLlE1Y7xq+0XgQKcFBPvRXqX5dccPEI4bTUQj25VvdCYP/7Mm7wg8CeTHqr1wXPsAH+jAycVN3HlWRz7VotAaGTs94ZZXVWB9qYt+HFYvOlEgiKZO78oSyxZ1DURwx0KysBDqBN00ES+Dy5EMl2bxF7yU0apIK75p/yjVMwool7vahFgaceJ83zPYe9DvYF3fkTA/2is2ReZzdq1mEo6EDWtiPcOVmfdA92yn6XuLyho+b8IAuZuzoS7tBpubYy4K8h0AKI2VlFy/YRmbCApk4d4KgYFCURPxgia0TgPJ8Yov4z3fSCtlHomCsaJ8IGqLmeqpfEp6ajQFBIrXVM/hPUaO43YIxEXJBDRdrPvO3o7OgtEl5PCyLk6xH8XdyVLCh6zt9T+iQkfoxr0HfLgYVViyTkGsH4/zCppA7kNM3YyhjoQRs0YXIvcr98KYvyJ0PlBj6CNWdy0EX2uZE2tzvp4EhPefy2/G2RN0tnPDGdRa9HJXsCrDWgzbCj2+a+f5tszKA2JwT4nyyK5yLaN1CUtJTSdoV8XzMr3PmtfNYglE53ZWY8KXUObwDoXbIzFNOPoEGczaK0dz1lP8FUuv4vCnD+TrX
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
