---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: taskflow-env-ai
  namespace: taskflow-staging
spec:
  encryptedData:
    PSU_AI_API_KEY: AgAigY08rDUbfpgTKrdMZ/ooSfBSXW460QMWTle2u06Hz9ikRPNzCVtlxvGej3CoxI5ZqZTBm77N20JHsSvyJ5FrNr/I4M7Pmu4la3U26fKe6+7fh1gjD47m4uYEGaOyQ7ZyFANcT6a5Lh0XCS0QPxg51Nyi/TwRc4xt4LKBSQttoS0qtCxMh/SFniMAnfkcU7jF/x5OwhnZQKqW2f1G/MCwfB2qhc7p+Nf3PKXGCIwOLW2b3KXfFC8YHxXBWHRJbZAHtndpvgRlvjaa7NVB/eVxZoXJdxLcvaCjiZGfk7ISzPLTeJkOyRYV0c5TNVGmLE4faan/0IlRVNX1ADszDMEGXMQfJE9qfNr5IYXvaIDITK0NtSSB1UKK+2sX7lmVZUjyMObu9GFxFiBmc4mOsxEPxzM2FgcUas8roRinu91tHZTImCSVFF0zPp2Q4m1VbFTZQTkFgULHlXpgJozO35ikRp+MsFYXRwnCC8DVckUxOHav48flkp5Nt79umBmlwyXQTO8jZKSqBNvvvcU421rZBKV4DqtqmvcW9h/IQS9Gs3apLOznyA84KUhSdeq4Nr+g2Q1/rRpKDuRPTsqgH8zDtmu6wnNvSrKxQIG8ftu9w3GcVt3vol9ZUjRLPRTO9WEyRRHZnqUiE0HI9WUziSXUwmIKj1JFU734KIFFXq34wkD4HUCs5OrpHyyeP6BAou4ZExT69FTQq68oyrELYiNfT9lkP8O5Lv+neaN216gUna2qQgdrepI/mxG00D2+y7CkAoWB4y3boJ/zQKnH7C6zCUydGai0oj8=
  template:
    metadata:
      name: taskflow-env-ai
      namespace: taskflow-staging
    type: Opaque
