---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: taskflow-extra-env
  namespace: taskflow-production
spec:
  encryptedData:
    PSU_AI_API_KEY: AgA1lUgUWYUOm7XgnlG0bDJ++rzB+Rwf2ITl7/WpCrvALzQ0YVDaxLg8nZvVuit1GIzXQHkad12NONnl6sH74CNFsr/kR0eUC5XMpGy+kKXhFEHLQFAWbBTtd7erKV0bpu3RLaUQqZOByKnR7LIMlalqp4QkD34u0ZkW8vtg3A/UFDijMugJSBxefClu0g1+keLDzxxWtsMKGTAd46gRNjxGm9oDxyZjR6ODKrM+p/9g3YnPzKS259mTxeh+6Nh3a22C5069Ws0nAe7TgkaC7w4bqHXla1Ey/oTX4VtikoyTMxuo52ws/+0A73NTqV0fMF5TLzAj87KmSU7CeJoyId9ZSQsvX23qlyQye5ujUzjjuA/faolZehe6cwPFCaihaj5cjta9q6UeuDNT2H2/hjNqfS7yblyL2G7vBp4E8rZZDi3z53Uc/DF8BDeWwnpTvsB0NiPiqAiJ2L0PU92fySKQbX79sokCjuY4MKchVRZfqEcnedVBlRn6sYSq6leCEZ4XEK0XYUhe/MomgGMNuYr8+L64Jy+xKV3odEtCAuoSmF/NsjlmM76z+7ydhqijtGsiRbWnl2p2kd9ByGdBgwlRTyN1+4uS9cRT8Z8pJun6kEgb+RDejxID2fw0wuMamwW5WI4AOwu5jGF7AaswdCEtpgW8W82TYjCPLyxuN5UI3ghqPtlmP8JtkBmQulwZa6yTsTwBQEsle/hyepBuais31SMLEC6pU500E004zKyQMCyhKOUjSNiQAXNl/8rGnji+b3ieDbZGaMjrTN84JHdNdLNwCJlPZ08=
  template:
    metadata:
      name: taskflow-extra-env
      namespace: taskflow-production
    type: Opaque
