---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: taskflow-extra-env
  namespace: taskflow-staging
spec:
  encryptedData:
    PSU_AI_API_KEY: AgCxSWtNxsf0oYtytB+8k0+fesp/XuE03psZXabmh+CT5Zp7IvuJEWirDjL1biSZhxqxeNhbzyBNpPZigZ6ROZmPau4iJYh4d0tUb9/sY0QK2gPbGwOG/HSvtvEcm/kchmkG7ZaC/fv4kW9lFOKCkxwisz4cbY7MoFUGBfGkUK82fqp0r9383CxvYWPQyg9yt7yUEAXKM1Hhpefp98nmYDmmhKMjdA5xO9C5IJ+dGmXke8hR16KB7jZIxW4Lg1k9XBlR+gcELXp08WfOEgCpFf89nqP2+5CyzsUisOr5QntVp2+8b1MckEpGsYPd7j2ShjbP1Lq7SFQxuj5e2JgaEDYb6bDrxS7x2txptOiS6oQQedzJ/JLSwZTYGNAUntCVtDycBB82kzkmtGNy0isP39Y9cZT5NWyQ39WfT9q+PLKkQVk5NrYDiWGQPGrfG1/fqRtQYsKwSVngmvfsZl7kgAkoplT2e6aBmAg7pOKiqt3BbdPbu/WbLMLMejgB0L46fBjQ3pQv2nwHr5N89euGaEISFvh3bfvSPy2cLeAqenrBthNWyJqZDQlhlq1TCXC7ry+wYPy7miuf7KEb95GimkjH4k5qCnSt2qG8HkMHKeHYrYdh9/q0qNmmfvxJVfjJ+Fq7PQFVm9Zs8GkmxEVHksFuW0PVEPldqr+O6eP5XM9X/maIqysOvKJq/O7pzXi4lr6PZxbVyawnGqButWnys5DKNazSpj8fMeQ7568+pkp0/XzE/PUaxYRpdVX1l2if2nR+DXD+/2qAAae23OaP0VDYCO5ZXkl4UHQ=
  template:
    metadata:
      name: taskflow-extra-env
      namespace: taskflow-staging
    type: Opaque
