replicaCount: 1
image:
  tag: "7543c89ad196ce671ff91b930136361b8266ae95"
config:
  nodeEnv: production
  appEnv: staging
migration:
  enabled: true
ingress:
  enabled: true
  className: traefik
  hosts:
    # nip.io resolves <anything>.172.30.58.25.nip.io to 172.30.58.25 (Traefik LB)
    - host: staging.alivefordie.site
      paths:
        - path: /
          pathType: Prefix
