replicaCount: 1
image:
  tag: "c05f57c27c77b418c7f5afee0727547830147895"
config:
  nodeEnv: production
  appEnv: staging
migration:
  enabled: true
ingress:
  enabled: true
  className: traefik
  hosts:
    # nip.io resolves <anything>.172.30.58.25.nip.io to 172.30.58.25 (Traefik LB)
    - host: staging.alivefordie.site
      paths:
        - path: /
          pathType: Prefix
