replicaCount: 1
image:
  tag: "22f6867c79730cd964e619256b2f887035bc0293"
config:
  nodeEnv: production
  appEnv: staging
migration:
  enabled: true
ingress:
  enabled: true
  className: traefik
  hosts:
    # nip.io resolves <anything>.172.30.58.25.nip.io to 172.30.58.25 (Traefik LB)
    - host: staging.172.30.58.25.nip.io
      paths:
        - path: /
          pathType: Prefix
