replicaCount: 1
image:
  tag: "1.0.0"
config:
  nodeEnv: production
  appEnv: production
migration:
  enabled: false
ingress:
  enabled: true
  className: traefik
  hosts:
    # nip.io resolves <anything>.172.30.58.25.nip.io to 172.30.58.25 (Traefik LB)
    - host: api.172.30.58.25.nip.io
      paths:
        - path: /
          pathType: Prefix
