{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow-chart.secretName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    {{- include "taskflow-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.password | quote }}
  JWT_SECRET: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
  R2_ACCOUNT_ID: {{ .Values.secrets.r2AccountId | quote }}
  R2_ACCESS_KEY_ID: {{ .Values.secrets.r2AccessKeyId | quote }}
  R2_SECRET_ACCESS_KEY: {{ .Values.secrets.r2SecretAccessKey | quote }}
  R2_BUCKET_NAME: {{ .Values.secrets.r2BucketName | quote }}
{{- end }}
